spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: ${DB}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 50MB
server:
  port: ${PORT:8880}
mybatis:
  mapper-locations: classpath:mapperxml/*.xml

file:
  upload:
    dir: C:\Users\Heqing\Pictures\Saved Pictures\


